-- Dataform transformation: fee_deductions

config {
  type: "table",
  name: "fee_deductions",
  description: "Transformation from fee_deductions",
  tags: ["transformation"],
}

WITH
cte_ext_tx_src AS (
  SELECT
    account_id,
    amount,
    transaction_type
  FROM ${ref('transactions')}
),

cte_agg_fees AS (
  SELECT
    ACCOUNT_ID,
    SUM(AMOUNT) AS TOTAL_FEES
  FROM cte_ext_tx_src AS src
  GROUP BY ACCOUNT_ID
),

cte_calc_tier AS (
  SELECT
    src.*,
    CASE WHEN src.TOTAL_FEES < -20 THEN 'low' WHEN src.TOTAL_FEES > -10 THEN 'high' ELSE 'medium' END AS FEE_TIER
  FROM cte_agg_fees AS src
)

SELECT
  j.ACCOUNT_ID,
  j.TOTAL_FEES,
  j.FEE_TIER
FROM cte_calc_tier AS j